name: 🛠 Install dependencies
steps:
  - uses: actions/cache@v3
    with:
      path: '**/node_modules'
      key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

  - if: steps.cache.outputs.cache-hit != 'true'
    run: yarn
