import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { QueryClient, useQuery } from 'react-query';

export const queryClient = new QueryClient();

const URL =
  'https://countriesnow.space/api/v0.1/countries/info?returns=flag,dialCode';

const Home: NextPage = () => {
  const query = useQuery('countries', () =>
    fetch(URL).then((res) => res.json())
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(6, 1fr)',
          gap: '1rem',
        }}
      >
        {query.data?.data.map((c: any, index: any) => (
          <div
            key={index}
            style={{ border: '1px solid black', padding: '20px' }}
          >
            <h2>Code:</h2>
            <span>{c.dialCode}</span>
            <h2>Flag:</h2>
            <img src={c.flag} alt={c.name} style={{ width: '100px' }} />
            <h2>Name:</h2>
            <span>{c.name}</span>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Home;
