import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { QueryClient } from 'react-query';
import Image from 'next/image';
import useFetchCountries from '../hooks/use-fetch-countries';
import { TCountry } from '../types';

export const queryClient = new QueryClient();

const URL =
  'https://countriesnow.space/api/v0.1/countries/info?returns=flag,dialCode';

const Home: NextPage = () => {
  const { status, countries } = useFetchCountries(URL);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {status === 'error' && <div>Error fetching data</div>}
      {status === 'loading' && <div>Fetching data...</div>}
      {status === 'success' && (
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(6, 1fr)',
            gap: '1rem',
          }}
        >
          {countries.map((c: TCountry, index: number) => (
            <div
              key={index}
              style={{ border: '1px solid black', padding: '20px' }}
            >
              <h2>Code:</h2>
              <span>{c.dialCode}</span>
              <h2>Flag:</h2>
              {/*
               * TODO: fix broken src url
               */}
              {/* <Image
                src={c.flag}
                alt={c.name}
                width={'100px'}
                height={'50px'}
                onError={() => {}}
              /> */}
              <img src={c.flag} alt={c.name} style={{ width: '100px' }} />
              <h2>Name:</h2>
              <span>{c.name}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default Home;
