import type { NextPage } from 'next';
import Head from 'next/head';

import SearchInput from '../../components/search-input';

const Countries: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Countries</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <SearchInput onChange={() => {}} value="yo" placeholder="" />
        </div>
    )
}

export default Countries;