import type { NextPage } from 'next';
import Head from 'next/head';

import App from '../../components/app';

const Countries: NextPage = () => {
    return (
        <div style={{
            display: 'flex',
            alignContent: 'center',
            justifyContent: 'center'
        }}>
            <Head>
                <title>Countries</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <App />
        </div>
    )
}

export default Countries;