name: 🇨🇾 Cypress run
description: 🇨🇾 Cypress run
inputs:
  workdir:
    description: '(path)'
    required: false
    default: ./
runs:
  using: 'composite'
  steps:
    - name: 🇨🇾 Cypress run
      uses: cypress-io/github-action@v4
      with:
        command: yarn cypress
        working-directory: ${{ inputs.workdir }}
        install: false
        build: yarn build
        start: yarn start --port 3000
        browser: chrome
        headless: true
