name: 🇨🇾 Cypress run
description: 🇨🇾 Cypress run
inputs:
  workdir:
    description: '(path)'
    required: false
    default: ./
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
       node-version: 16

    - name: 🇨🇾 Cypress run
      uses: cypress-io/github-action@v5
      with:
        working-directory: ${{ inputs.workdir }}
        install: false
        browser: chrome
        build: yarn build
        start: yarn start --port 3000
