name: 🇨🇾 Cypress run
description: 🇨🇾 Cypress run
inputs:
  workdir:
    description: '(path)'
    required: false
    default: ./
runs:
  using: 'composite'
  steps:
    - name: 🇨🇾 Cypress run
      uses: cypress-io/github-action@v5
      with:
        working-directory: ${{ inputs.workdir }}
        install: false
        build: yarn build
        start: yarn start
      env:
        PUBLIC_KEY: ${{ secrets.EMAILJS_PUBLIC_KEY }}
        SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
        TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
