name: 🇨🇾 Cypress run
description: 🇨🇾 Cypress run
inputs:
  workdir:
    description: '(path)'
    required: false
    default: ./
runs:
  using: 'composite'
  steps:
    - name: 🇨🇾 Cypress run
      uses: cypress-io/github-action@v3
      with:
        working-directory: ${{ inputs.workdir }}
        install: false
        browser: chrome
        build: yarn build
        start: yarn start
        wait-on: 'http://localhost:3000'
