name: 🇨🇾 Cypress run
description: 🇨🇾 Cypress run
inputs:
  workdir:
    description: '(path)'
    required: false
    default: ./
  publicKey:
    description: 'EmailJS public key'
    required: true
  serviceId:
    description: 'EmailJS service id'
    required: true
  templateId:
    description: 'EmailJS template id'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 🇨🇾 Cypress run
      uses: cypress-io/github-action@v5
      with:
        working-directory: ${{ inputs.workdir }}
        install: false
        build: yarn build
        start: yarn start
      env:
        PUBLIC_KEY: ${{ inputs.publicKey }}
        SERVICE_ID: ${{ inputs.serviceId }}
        TEMPLATE_ID: ${{ inputs.templateId }}
