name: update pull request
on: [push]

jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: tzkhan/pr-update-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        base-branch-regex: '[a-z\d-_.\\/]+'
        head-branch-regex: 'github-action-to-change-pr-name'
        title-template: '[%headbranch%] '
        body-template: |
          Merging into '%basebranch%'
        body-update-action: 'suffix'
        body-uppercase-base-match: false